game api 관련 react query hook 작성
CHZZK-Study/Balance-Talk-Frontend pull request #128
Opened 2024-06-29 07:36 UTC by areumH

## 💡 작업 내용

- [x] game api 엔드 포인트 및 타입 작성
- [x] game api axios 함수 작성
- [x] game api react query hook 작성 

## 💡 자세한 설명
- 게임을 조회하는 함수가 많아 `useGetGameQuery.ts` 파일에 모아두었습니다.
- `useEditGameMutation.ts` 훅은 Game 뿐만 아니라 postId도 함께 넘겨주어야 하기 때문에 한 번에 모두 넘겨주는 것 보다 postId를 먼저 넘겨준 뒤 Game 값들을 넘겨주는 것이 더 깔끔하다고 생각되어 `useMutation` 함수를 바로 return 해주었습니다!

 예시) 
```javascript
export const useEditGameMutation = (postId: number) => {
  const queryClient = useQueryClient();

  const editGameMutate = useMutation({
    mutationFn: (data: Game) => patchGame(postId, { ...data }),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: ['games', postId],
      });
    },
  });

  return editGameMutate;
};

// * * * * *

const editGameMutation = useEditGameMutation(gameId);

const handleEditGame = () => {
  editGameMutation.mutate({title, options, storedImageName});
};
```

## 📗 참고 자료 (선택)

## 📢 리뷰 요구 사항 (선택)

## 🚩 후속 작업 (선택)

## ✅ 셀프 체크리스트

- [ ] PR 제목을 형식에 맞게 작성했나요?
- [ ] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있나요? (master/main이 아닙니다.)
- [ ] 이슈는 close 했나요?
- [ ] Reviewers, Labels, Projects를 등록했나요?
- [ ] 작업 도중 문서 수정이 필요한 경우 잘 수정했나요?
- [ ] 테스트는 잘 통과했나요?
- [ ] 불필요한 코드는 제거했나요?

closes #127

2024-06-29 08:47 UTC, hsgh085 requested changes
game api들 함수로 정리하고, 리액트 쿼리 훅으로 만드시느라 고생하셨습니다~!👏

저희가 컨벤션 정한 바에 따르면 게임 조회 리액트 쿼리들도 모두 파일 각각 하나로 만들어 사용하는 것이 맞다고 생각해요!

바쁘시겠지만 수정 부탁드립니다~!

2024-06-29 08:47 UTC, hsgh085 commented on src/api/game.ts
> +export const getGameById = async (postId: number) => {
지난번 회의에서 type들을 모두 type파일에 정리해서 사용하기로 컨벤션을 정했듯이! 저희 타입을 number로 명시하기 보다, type 파일에 정의한 타입들을 활용하면 좋을 것 같습니다😀

2024-06-29 08:47 UTC, hsgh085 commented on src/api/game.ts
> +  const { data } = await axiosInstance.delete<string>(
return type 또한 마찬가지로 string으로 명시하기 보다 type 파일에 정의해서 사용하면 좋을 것 같습니다!

2024-06-29 09:41 UTC, areumH commented on src/api/game.ts
> +  const { data } = await axiosInstance.delete<string>(
제가 놓친 부분이 많았네요.. 짚어주셔서 감사합니다 🥹🥹
수정하여 커밋 올렸습니다 !!

2024-06-29 09:59 UTC, hsgh085 approved these changes
수정 사항 확인했습니다~! 고생하셨어요!!

2024-06-29 11:29 UTC, areumH commented on src/constants/api.ts
> +  DELETE_GAME: (postId: number) => `/games/${postId}`,
제가 엔드 포인트를 빼놓고 수정했네요 🫢
새로 커밋했습니다 !

2024-06-29 11:34 UTC, areumH commented on src/types/type.ts
> +export type PostId = number;
오 Id로 변경하는 것 좋은 것 같아요!! 파일명도 api가 더 괜찮은 것 같네요 😮
수정님도 확인하시면 결정된 의견 반영하여 수정하겠습니다 !!

2024-06-29 13:49 UTC, kwaksj329 commented on src/types/type.ts
> +export type PostId = number;
확인했습니다. 저도 희선님께서 말씀하신대로 반영되면 좋을 것 같아요!

2024-06-29 13:54 UTC, kwaksj329 approved these changes
수정사항까지 확인 완료했습니다! 고생 많으셨어요 👍🏻

2024-07-01 07:52 UTC, hsgh085 commented on src/types/api.ts
> +};
Pageable 타입을 api파일에 정의하셨군요! 혹시 통일성을 위해서 pagination.ts 파일에 정의된 PaginationType도 api 파일로 옮겨주시거나 또는 Pageable 타입을 pagination.ts 에 옮겨주실 수 있을까요??

2024-07-01 08:49 UTC, areumH commented on src/types/api.ts
> +};
pagination.ts 파일로 옮겨두었습니다!!

2024-07-01 12:33 UTC, merged